### PR TITLE
Addition of a paragraph about compiled binaries and config files

### PR DESCRIPTION
**Pull request by aurelg**
Both compiled binaries and configuration files should be excluded from the version control system.

### CODE REVIEW

**Comment by aurelg** [comment]
Sorry, typos, closing this PR.

**Comment by jkitzes** [comment]
While this is both true and important, I also think that it might be above and beyond the types of files that the audience for this paper is going to be working with regularly. @gvwilson ?

**Comment by jennybc** [comment]
If we decide binaries are in scope, yes agree they should not be under version control.

I'm less sure if I agree about configuration files. It depends on your definition of "configuration file". For example, I often believe in putting `.gitignore` under version control or the file that records configuration for an RStudio project. What sort of config are we talking about and what's the rationale for excluding? I suspect we should not get into this here.

**Comment by gvwilson** [comment]
I think we should take this out - the paper is already overly long, and 
there's no way we can give people an accurate understanding of what we 
mean without adding at least another half a page (maybe more).

**Comment by aurelg** [comment]
@jennybc The lack of clear definition of configuration file is part of the problem, and until it is solved, there's probably no point writing about how they should be handled.

BTW, I realized that we might not understand "source code" in the same way. My understanding was about source code that may be compiled or interpreted, but anyway packaged, distributed and deployed. This includes C, Java, R, python, etc, and  even PHP if it's about a website to provide the scientific community with an user interface to a tool which is developed in house. I personally [wrote](http://www.ncbi.nlm.nih.gov/pubmed/17380512) [many](https://www.ncbi.nlm.nih.gov/pubmed/21541955) [of](http://www.ncbi.nlm.nih.gov/pubmed/19130502) [them](https://www.ncbi.nlm.nih.gov/pubmed/21624888), alone or in [collaboration](http://www.ncbi.nlm.nih.gov/pubmed/22661580) , hence my bias. I first thought RStudio was a single user workspace for day to day research, for which backups are perhaps more suitable than VCS, but I agree: to some extent, it's also source code.

This diversity of situation might not be clear for the audience as well, and its interpretation might thus be relative to its knowledge and practices. Writing guidelines is no use if readers think they're not part of the audience, or if they believe they are whereas they are not. I agree with @jkitzes: this is beyond the scope of this paper, even though it is of major importance WRT software carpentry.

Back to configuration files: in most research software I know, there are both per-use and system-wide configurations. Files are generally used for the latter, but it's also common (bad) practice to store them in the DVCS, as a consequence of which every contributor have to edit in files that are under version control in order to make the software run on its own machine, which is a bug-prone mess, if not a major security threat.

@gvwilson I wrote this paragraph because from my own research experience, both alone and as a collaborative effort, I do think it's very important, but I understand the papier is already long. In the end, I'm not an author and it's consequently up to you to decide :)

**Comment by gvwilson** [comment]
Thanks very much for the contribution, but I think it will be out of scope for the intended readership of this paper (and yes, we're already over-long).

**Pull request closed without merging**
