### PR TITLE
Replace 'novices' with 'beginners'

### PR DESCRIPTION
**Pull request by lexnederbragt**
I worry the word 'novice' in this paper may be off-putting for the intended audience, but given I am not a native English speaker I may be wrong here.

### CODE REVIEW

**Comment by gvwilson** [comment]
I think either is OK, but agree that we should be consistent. Anyone else have a preference?

**Comment by jkitzes** [comment]
Either is OK, I lean slightly towards 'beginner'. Even though they're synonyms by the dictionary, 'novice' to me has slightly stronger connotations of lack of competence, while beginner is more neutrally someone who's just getting started.

**Comment by jennybc** [comment]
I'm happy with either. Sometimes I use "newcomer", in case anyone likes that. But I don't mean to muddy the water further.

**Comment by beroe** [comment]
I think `beginner` might be preferable, for the connotations that Lex brought up.

**Comment by kcranston** [comment]
I like Jenny's suggestion of newcomer - it lacks any negative connotation.

**Comment by beroe** [comment]
I agree `newcomer` could work a couple times, but would it sound weird all six places that `novices` occurs?

**Comment by gvwilson** [comment]
Fixed by using a mix of terms.

**Pull request closed without merging**
